language: node_js
sudo: required
node_js:
  - "9"
env:
  global:
    - DOCKER_FOLDER: "$TRAVIS_BUILD_DIR/"
    - DB_IMAGE: metacell/scidash_db
    - GEPPETTO_IMAGE: metacell/scidash_virgo
    - SCIDASH_IMAGE: metacell/scidash
    - DB_CONTAINER: scidash_db
    - GEPPETTO_CONTAINER: scidash_virgo
    - SCIDASH_CONTAINER: scidash
    - DEFAULT_BRANCH: development
    - LANDING_PAGE: "http://127.0.0.1:8000"
    - COMMIT: ${TRAVIS_COMMIT::8}
services:
  - docker
before_install:
  - export BUILD_TYPE=`if [ "$TRAVIS_BRANCH" == "vfb_geppetto_application" ]; then echo "development"; else echo "release"; fi`
  - export VFB_REPO=$(echo ${TRAVIS_REPO_SLUG##*/} | awk '{gsub(/\-/,"_",$0);gsub(/\./,"_",$0);print toupper($0)}')
  - export REPO=$(echo ${TRAVIS_REPO_SLUG} | awk '{gsub(/\./,"_",$0);print tolower($0)}')
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo ${TRAVIS_BRANCH/\//-}; fi`
  - export TAG=`if [ "$BUILD_TYPE" == "development" ]; then echo "$TAG-development"; else echo "$TAG"; fi`
install:
  - npm install jest@24.8.0 puppeteer@1.17.0 jest-puppeteer@4.3.0 @babel/preset-env@7.4.5 url-join@4.0.0 @babel/core@7.4.5
before_script:
  - docker pull metacell/scidash_virgo:development || true
script:
  - git clone -b feature/393 https://github.com/Metacell/scidash.git || true
  - echo -e "travis_fold:start:Docker_Build" || true
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo -e "Building scidash database container" || true
  - travis_retry docker build --build-arg SCIDASH_BRANCH=feature/393 -f ./scidash/service/docker/Dockerfile-postgres -t=$DB_IMAGE:$TAG $DOCKER_FOLDER || travis_terminate 1
  - sleep 5
  - echo -e "Building geppetto virgo container" || true
  - travis_retry docker build -f ./scidash/service/docker/Dockerfile-virgo -t=$GEPPETTO_IMAGE:$TAG $DOCKER_FOLDER || travis_terminate 1
  - sleep 5
  - echo -e "Building scidash container" || true
  - travis_retry docker build --build-arg targetBranch==feature/393 -f ./scidash/service/docker/Dockerfile-scidash -t=$SCIDASH_IMAGE:$TAG $DOCKER_FOLDER || travis_terminate 1
  - sleep 5
  - echo -e "Starting scidash docker compose" || true
  - cd ./scidash/service/deployment || true
  - travis_retry docker-compose up -d || travis_terminate 1
  - cd -
  - sleep 60;
  - bash $TRAVIS_BUILD_DIR/utilities/tests/scripts/test_geppetto_server.sh
  - echo -e "travis_fold:end:Startup_Server1" || true
  - docker logs $SCIDASH_CONTAINER || true
  - docker logs $GEPPETTO_CONTAINER || true
  - docker logs $DB_CONTAINER || true
  - sleep 60
  - echo -e "travis_fold:start:Startup_Server2" || true
  - bash $TRAVIS_BUILD_DIR/utilities/tests/scripts/test_geppetto_server.sh
  - sleep 30
  - echo -e "travis_fold:end:Startup_Server2" || true
  - http_status=$(curl -s -I $1 $LANDING_PAGE | grep HTTP/1.1 | awk {'print $2'})
  - echo "$http_status"
  - while [ "$http_status" == "404" ]; do
      echo "Restart run. Printing logs for debugging purposes";
      sudo docker cp $GEPPETTO_CONTAINER:/opt/virgo/serviceability/logs/log.log /etc;
      tail -n 200 /etc/log.log;
      docker stop $(docker ps -a -q);
      sleep 10;
      docker rm $(docker ps -a -q);
      sleep 10;
      travis_retry docker-compose up -d;
      bash $TRAVIS_BUILD_DIR/utilities/tests/scripts/test_geppetto_server.sh;
      sleep 60;
      http_status=$(curl -s -I $1 $LANDING_PAGE | grep HTTP/1.1 | awk {'print $2'});
      echo "Done restarting $http_status";
    done;
  - travis_retry npm test
  - docker ps -a;
  - sudo docker cp $GEPPETTO_CONTAINER:/opt/virgo/serviceability/logs/log.log /etc;
  - tail /etc/log.log -n 200
  - docker stop $(docker ps -a -q)
  - docker rm $(docker ps -a -q)
